"""Markdown rendering: README (curated list + companies), daily and weekly digests."""
from __future__ import annotations

from collections import defaultdict
from datetime import timedelta

from common import COMPANIES, CONFIG, ROOT, now_utc, today

TOPICS = CONFIG["topics"]


def _esc(s: str) -> str:
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


def _authors(p: dict, n: int = 3) -> str:
    a = p.get("authors") or []
    return ", ".join(a[:n]) + (" et al." if len(a) > n else "")


def _code(p: dict) -> str:
    if not p.get("code_url"):
        return "—"
    stars = p.get("stars")
    label = f"⭐ {stars:,}" if stars is not None else "code"
    return f"[{label}]({p['code_url']})"


def _tldr(p: dict) -> str:
    llm = p.get("llm") or {}
    en, zh = llm.get("tldr"), llm.get("tldr_zh")
    if en:
        return _esc(en + (f"<br>{zh}" if zh else ""))
    # Heuristic fallback: first sentence of the abstract.
    first = p["abstract"].split(". ")[0]
    return _esc(first[:220] + ("…" if len(first) > 220 else ""))


def _paper_row(p: dict) -> str:
    title = f"[{_esc(p['title'])}]({p['url']})"
    venue = p.get("venue") or "arXiv"
    cites = p.get("citations")
    meta = f"{venue}<br>{p['published'][:7]}" + (f"<br>📑 {cites}" if cites else "")
    return f"| {title}<br><sub>{_esc(_authors(p))}</sub> | {meta} | {_code(p)} | {_tldr(p)} |"


TABLE_HEAD = "| Paper | Venue / Date | Code | TL;DR |\n|---|---|---|---|"


def _news_line(it: dict) -> str:
    icon = {"blog": "📝", "repo": "💻"}.get(it["kind"], "📰")
    return f"- {icon} {it['date']} [{_esc(it['title'])}]({it['url']}) <sub>{_esc(it['source'])}</sub>"


def companies_section(news: dict, days: int = 14, per_company: int = 5) -> str:
    since = (now_utc() - timedelta(days=days)).strftime("%Y-%m-%d")
    by_c = defaultdict(list)
    for it in news.values():
        if it["date"] >= since:
            by_c[it["company"]].append(it)
    out = [f"## 🏢 Industry Tracker\n\nLatest {days} days of news, official blog posts and new "
           "open-source repos from tracked companies. Full daily feed in [`daily/`](daily/).\n"]
    for c in COMPANIES:
        items = sorted(by_c.get(c["name"], []), key=lambda x: x["date"], reverse=True)
        # Prefer primary sources (blog, repo) over press coverage.
        items = ([i for i in items if i["kind"] != "news"][:2] + [i for i in items if i["kind"] == "news"])[:per_company]
        out.append(f"<details><summary><b>{c['name']}</b> ({len(by_c.get(c['name'], []))})</summary>\n")
        out.extend(_news_line(i) for i in items)
        if not items:
            out.append("- _No recent items._")
        out.append("\n</details>\n")
    return "\n".join(out)


def readme(curated: list[dict], stats: dict, news: dict) -> str:
    by_topic = defaultdict(list)
    for p in curated:
        by_topic[p["topic"]].append(p)
    toc = [f"- [{t['name']}](#{_anchor(t['name'])}) ({len(by_topic[k])})"
           for k, t in TOPICS.items() if by_topic[k]]
    parts = [f"""# 🚗 Awesome Autonomous Driving Radar

> A **curated, auto-maintained** list of ~{CONFIG['curated_size']} high-quality, open-source autonomous-driving
> papers from the last {CONFIG['window_months']} months, plus a daily industry tracker.
> Updated {today()} · {stats['tracked']:,} papers tracked · {len(curated)} curated.

**Selection rule.** A paper is listed only if it (1) is primarily about autonomous driving,
(2) has public code, and (3) shows at least one strong signal: accepted at a top venue
(CVPR / ICCV / ECCV / NeurIPS / ICLR / ICML / CoRL / RSS / TPAMI, or ICRA / IROS / AAAI / RA-L),
≥200 GitHub stars, ≥3 citations / month, or a well-known lab with traction. Papers are then ranked by a
composite score (venue, stars, citation velocity, LLM rubric for novelty / rigor / impact, SOTA claims)
with a per-topic cap. See [`scripts/rank.py`](scripts/rank.py).

📅 [Daily digests](daily/) · 🗓️ [Weekly digests](weekly/) · 📦 [Raw data](data/)

## Contents

""" + "\n".join(toc) + "\n- [Industry Tracker](#-industry-tracker)\n"]
    for k, t in TOPICS.items():
        ps = sorted(by_topic[k], key=lambda p: p["score"], reverse=True)
        if not ps:
            continue
        parts.append(f"## {t['name']}\n\n{TABLE_HEAD}\n" + "\n".join(_paper_row(p) for p in ps) + "\n")
    parts.append(companies_section(news))
    parts.append("---\n\n<sub>Generated by [`scripts/run.py`](scripts/run.py). "
                 "Scores and summaries are automated and may contain mistakes; "
                 "PRs to [`config.yaml`](config.yaml) `curation.include/exclude` are welcome.</sub>\n")
    return "\n".join(parts)


def _anchor(name: str) -> str:
    import re
    return re.sub(r"[^\w\- ]", "", name.lower()).strip().replace(" ", "-")


def daily(date: str, new_papers: list[dict], news_items: list[dict], summary: str | None) -> str:
    ps = sorted(new_papers, key=lambda p: p["score"], reverse=True)
    picks = [p for p in ps if p.get("code_url")][:15]
    rest = [p for p in ps if p not in picks][:25]
    out = [f"# Autonomous Driving Daily · {date}\n",
           f"{len(new_papers)} new driving papers · {len(news_items)} industry items\n"]
    if summary:
        out.append("## 📰 Industry summary\n\n" + summary + "\n")
    if picks:
        out.append("## ⭐ New papers with code\n\n" + TABLE_HEAD + "\n" + "\n".join(_paper_row(p) for p in picks) + "\n")
    if rest:
        out.append("## Other new papers\n")
        out.extend(f"- [{_esc(p['title'])}]({p['url']}) · {p.get('venue') or 'arXiv'} · "
                   f"{TOPICS[p['topic']]['name'].split(' ')[0]}" for p in rest)
        out.append("")
    if news_items:
        out.append("## 🏢 Companies\n")
        by_c = defaultdict(list)
        for it in news_items:
            by_c[it["company"]].append(it)
        for c in COMPANIES:
            if by_c.get(c["name"]):
                out.append(f"### {c['name']}\n")
                out.extend(_news_line(i) for i in sorted(by_c[c["name"]], key=lambda x: x["date"], reverse=True)[:8])
                out.append("")
    return "\n".join(out)


def weekly(week: str, papers: list[dict], news_items: list[dict], summary: str | None) -> str:
    ps = sorted(papers, key=lambda p: p["score"], reverse=True)[:25]
    out = [f"# Autonomous Driving Weekly · {week}\n",
           f"{len(papers)} new driving papers this week · {len(news_items)} industry items\n"]
    if summary:
        out.append("## 📰 Industry summary\n\n" + summary + "\n")
    if ps:
        out.append("## 🏆 Top papers of the week\n\n" + TABLE_HEAD + "\n" + "\n".join(_paper_row(p) for p in ps) + "\n")
    return "\n".join(out)


def write(rel: str, text: str) -> None:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
